sonarqube8/base/postgresql-dc.yaml
sonarqube8/base/sonarqube-dc.yaml

Add some labels and annotations for Developer view

Add labels/annotations

---

apicast/base/apicast-dc.yaml
apicast/base/apicast-route.yaml
apicast/base/apicast-svc.yaml
apicast/base/kustomization.yaml
apicast/overlays/default/kustomization.yaml
apicast/overlays/prod/kustomization.yaml
apicast/overlays/prod/patch-prod-dc.yaml
apicast/overlays/stage/kustomization.yaml
apicast/overlays/stage/patch-stage-dc.yaml

Adds kustomization for apicast including staging and production gateways

Add support for apicast deployment

---

rhsso/rhsso-standalone/README.md
rhsso/rhsso-standalone/base/kustomization.yaml
rhsso/rhsso-standalone/base/sso-credential-secret.yaml
rhsso/rhsso-standalone/base/sso-db-secret.yaml
rhsso/rhsso-standalone/base/sso-discovery-svc.yaml
rhsso/rhsso-standalone/base/sso-postgresql-deploy.yaml
rhsso/rhsso-standalone/base/sso-postgresql-pvc.yaml
rhsso/rhsso-standalone/base/sso-postgresql-svc.yaml
rhsso/rhsso-standalone/base/sso-probes-cm.yaml
rhsso/rhsso-standalone/base/sso-route.yaml
rhsso/rhsso-standalone/base/sso-ss.yaml
rhsso/rhsso-standalone/base/sso-svc.yaml
rhsso/rhsso-standalone/overlays/default/kustomization.yaml
rhsso/rhsso-standalone/overlays/default/namespace.yaml

Deploy RH-SSO without operator since operator currently has issues.

SSO Standalone (No Operator)

---

pipelines-operator/README.md

Fixed openshift-pipelines-operator url reference

Fix 404 on URL

---

opendatahub-operator/README.md
opendatahub-operator/base/kustomization.yaml
opendatahub-operator/base/opendatahub-operator-subscription.yaml
opendatahub-operator/overlays/beta/README.md
opendatahub-operator/overlays/beta/kustomization.yaml
opendatahub-operator/overlays/beta/patch-channel-and-version.yaml

Hey guys, I'm working on setting up a cluster using your repo as a reference so I figured I would contribute back some of the operators that I'm setting up that you don't currently have in the catalog.

add odh operator

---

openshift-container-storage-operator/overlays/stable-4.6/README.md
openshift-container-storage-operator/overlays/stable-4.6/patch-channel-and-version.yaml

Updating OCS version to the latest startingCSV.

OCS update

---

amq-streams-operator/README.md
amq-streams-operator/overlays/amq-streams-1.7.x/README.md
amq-streams-operator/overlays/amq-streams-1.7.x/kustomization.yaml
amq-streams-operator/overlays/amq-streams-1.7.x/patch-channel-and-version.yaml

Adding new amq-streams-1.7.x channel

Amq streams 1.7.x

---

openshift-serverless-knative-eventing/overlays/knative-kafka/kustomization.yaml
test.sh

Fixing an resources reference to a filename that was incorrect

fix filename error in serverless-knative-eventing

---

openshift-serverless-operator/overlays/4.6/kustomization.yaml
openshift-serverless-operator/overlays/4.7/kustomization.yaml

resolves #26 
Removed some bad references that were left over from a refactor/copy/paste issue.

remove kafka-instance ref

---

opendatahub-operator/README.md
openshift-container-storage-noobaa/README.md
openshift-container-storage-operator/README.md
openshift-pipelines-operator/README.md
openshift-serverless-knative-eventing/README.md
openshift-serverless-knative-serving/README.md
openshift-serverless-operator/README.md

chanel to channel spelling fix

---

CONTRIBUTING.md
README.md

Updated the sample dir structure in the `CONTRIBUTING` guide.
@gnunn1 , can you take a look and merge if you're happy with it?

Clarify dir structure in CONTRIBUTING.md

---

acs-operator/README.md

I found out the condition changes after an upgrade of ACS, this updates the README.md to include the additonal check.

Update health check to handle upgrade

---

.github/workflows/kustomize-lint.yaml

Updated the action names to be a little more verbose.
Also updated the action to run on all branches so that it will run on a developers forked branch before submitting a PR.

Action rename

---

advanced-cluster-management/instance/base/multiclusterhub.yaml
ansible-automation-platform/instance/base/automationcontroller.yaml

Do not assume CRD exists

---

advanced-cluster-security-operator/instance/overlays/internal-registry-integration/stackrox-image-integration-update-job.yaml
ansible-automation-platform/instance/base/automationcontroller.yaml
ansible-automation-platform/operator/overlays/early-access/kustomization.yaml
apicast/overlays/stage/kustomization.yaml
jenkins2/overlays/m2-pvc-nexus2-sonarqube8-settings/jenkins-cm.yaml
jenkins2/overlays/m2-pvc/jenkins-cm.yaml
jenkins2/overlays/nexus2-settings/jenkins-cm.yaml
openshift-container-storage-noobaa/base/backingstore.yaml
openshift-container-storage-noobaa/base/noobaa.yaml
openshift-serverless/instance/knative-eventing/overlays/knative-kafka/knative-kafka.yaml
rhsso/rhsso-instance/overlays/crc/oauth-rhsso-openid.yaml
rhsso/rhsso-instance/overlays/crc/openshift-client.yaml
rhsso/rhsso-instance/overlays/rhpds/oauth-rhsso-openid.yaml
rhsso/rhsso-instance/overlays/rhpds/openshift-client.yaml
rhsso/rhsso-operator/base/approval-and-cert-job.yaml

Remove extra spaces at end of line

---

advanced-cluster-management/operator/overlays/release-2.3/kustomization.yaml
advanced-cluster-security-operator/operator/overlays/latest/kustomization.yaml
ansible-automation-platform/instance/overlays/default/kustomization.yaml
ansible-automation-platform/operator/overlays/early-access/kustomization.yaml
compliance-operator/operator/base/kustomization.yaml
compliance-operator/operator/overlays/release-0.1/kustomization.yaml
container-security-operator/overlays/v3.5/kustomization.yaml
openshift-logging/instance/overlays/default/kustomization.yaml
openshift-logging/operator/overlays/stable/kustomization.yaml

Resolving spacing issue to update for #62

remove extra space after hyphen and fix indentation levels

---

openshift-container-storage-noobaa/base/backingstore.yaml

Remove unusued comment

---

grafana-operator/base/instance/grafana.yaml

Update true/false to correct capitolization

---

advanced-cluster-security-operator/instance/base/namespace.yaml
compliance-operator/operator/base/namespace.yaml
cost-management-operator/overlays/default/namespace.yaml
grafana-operator/overlays/example/namespace.yaml
grafana-operator/overlays/user-app-example/namespace.yaml
namespace-configuration-operator/overlays/default/namespace.yaml
prometheus-operator/overlays/example/namespace.yaml

remove extra space after colon

---

sealed-secrets-operator/scripts/get-sealed-secret-key.sh

added flag mode to the mkdir command. setting ~./bitnami to 700 due to security

---

openshift-gitops-operator/README.md
openshift-gitops-operator/overlays/preview/README.md
openshift-gitops-operator/overlays/preview/kustomization.yaml
openshift-gitops-operator/overlays/preview/patch-channel.yaml
openshift-gitops-operator/overlays/stable/README.md

Add preview channel
Update docs to reflect current channels/versions

Openshift-gitops channels

---

openshift-data-foundation-operator/README.md
openshift-data-foundation-operator/operator/base/kustomization.yaml
openshift-data-foundation-operator/operator/base/namespace.yaml
openshift-data-foundation-operator/operator/base/openshift-data-foundation-operator-operatorgroup.yaml
openshift-data-foundation-operator/operator/base/openshift-data-foundation-operator-subscription.yaml
openshift-data-foundation-operator/operator/overlays/stable-4.9/README.md
openshift-data-foundation-operator/operator/overlays/stable-4.9/kustomization.yaml
openshift-data-foundation-operator/operator/overlays/stable-4.9/patch-channel.yaml

OCS has been renamed to ODF and the subscription has been changed accordingly.

Add ODF operator with stable-4.9 overlay.

---

grafana-operator/base/operator/grafana-subscription.yaml

Updated Grafana subscription channel from `alpha` to `v4`.

Updated grafana subscription channel.

---

oauth/README.md
oauth/overlays/ldap/kustomization.yaml
oauth/overlays/ldap/oauth-ldap-patch.yaml

This pull request adds an ldap overlay. There is also an example remote usage added to the oauth/README.md. Feedback to this approach is welcome

Add oauth/overlays/ldap

---

jenkins2/base/jenkins-pvc.yaml
jenkins2/overlays/m2-pvc-nexus2-sonarqube8-settings/maven-m2-pvc.yaml
jenkins2/overlays/m2-pvc/maven-m2-pvc.yaml
migration-toolkit-apps/base/mta-web-console-mta-web-claim-pvc.yaml
migration-toolkit-apps/base/mta-web-console-postgresql-claim-pvc.yaml
nexus2/base/nexus-pvc.yaml
sealed-secrets-operator/scripts/get-sealed-secret-key.sh
selenium/base/selenium-base-bc.yaml
selenium/base/selenium-hub-bc.yaml
selenium/base/selenium-node-base-bc.yaml
selenium/base/selenium-node-chrome-bc.yaml
selenium/base/selenium-node-chrome-debug-bc.yaml
selenium/base/selenium-node-firefox-bc.yaml
selenium/base/selenium-node-firefox-debug-bc.yaml
sonarqube8/base/postgresql-data-pvc.yaml
sonarqube8/base/sonarqube-data-pvc.yaml

This PR fixes:
- ﻿https://github.com/redhat-cop/gitops-catalog/issues/17
- https://github.com/redhat-cop/gitops-catalog/issues/79
- https://github.com/redhat-cop/gitops-catalog/issues/80

Fix couple of open issues

---

advanced-cluster-management/instance/README.md
advanced-cluster-management/instance/base/kustomization.yaml
advanced-cluster-management/instance/base/subscription-admin.yaml
advanced-cluster-management/instance/observability/00-namespace.yaml
advanced-cluster-management/instance/observability/01-acm-observability-bucket.yaml
advanced-cluster-management/instance/observability/02-install-observability.yaml
advanced-cluster-management/instance/observability/03-multiclusterobservability.yaml
advanced-cluster-management/instance/observability/kustomization.yaml

This is adding support to deploy ACM observability stack using GitOps.

ACM observability

---

cert-manager-operator/operator/base/kustomization.yaml

Added namespace for cert-manager-operator

Added namespace for cert-manager-operator

---

sealed-secrets-operator/base/kustomization.yaml

Fix issue with sealed-secrets images being nuked in quay.io
https://github.com/bitnami-labs/sealed-secrets/issues/822

Patch image reference

---

ansible-automation-platform/operator/overlays/stable-2.1-cluster-scoped/kustomization.yaml

Do not speficy targetNamespaces for cluster-scoped AAP

---

openshift-gitops-operator/README.md
openshift-gitops-operator/overlays/gitops-1.5/README.md
openshift-gitops-operator/overlays/gitops-1.5/kustomization.yaml
openshift-gitops-operator/overlays/gitops-1.5/patch-channel.yaml
openshift-gitops-operator/overlays/latest/README.md
openshift-gitops-operator/overlays/latest/kustomization.yaml
openshift-gitops-operator/overlays/latest/patch-channel.yaml
openshift-gitops-operator/overlays/stable/README.md

Added the "latest" and "gitops-1.5" channels overlays to openshift-gitops-operator.

Added latest and gitops-1.5 channels to openshift-gitops-operator

---

openshift-data-foundation-operator/README.md
openshift-data-foundation-operator/operator/overlays/stable-4.10/README.md
openshift-data-foundation-operator/operator/overlays/stable-4.10/kustomization.yaml
openshift-data-foundation-operator/operator/overlays/stable-4.10/patch-channel.yaml

Add ODF 4.10 overlays

---

advanced-cluster-management/operator/README.md
advanced-cluster-management/operator/overlays/release-2.5/kustomization.yaml

Add ACM 2.5

---

ansible-automation-platform/operator/README.md

Updates the readme for the AAP operator to correctly reflect what overlays are available.

Update AAP operator readme

---

CONTRIBUTING.md

Noticed a couple of issues so thought I'd just clean them up

Fixed some minor spelling and grammar mistakes

---

submariner-operator/README.md
submariner-operator/base/kustomization.yaml
submariner-operator/base/namespace.yaml
submariner-operator/base/operatorgroup.yaml
submariner-operator/base/subscription.yaml
submariner-operator/overlays/stable-0-12/kustomization.yaml

Added required manifests for the submariner operator

Added submariner operator to catalog

---

openshift-api-for-data-protection-operator/README.md
openshift-api-for-data-protection-operator/base/kustomization.yaml
openshift-api-for-data-protection-operator/base/namespace.yaml
openshift-api-for-data-protection-operator/base/operatorgroup.yaml
openshift-api-for-data-protection-operator/base/subscription.yaml
openshift-api-for-data-protection-operator/overlays/stable/kustomization.yaml

Added required manifests for the oadp operator

Added adp operator

---

openshift-dev-spaces/instance/README.md
openshift-dev-spaces/instance/base/checluster.yaml
openshift-dev-spaces/instance/base/kustomization.yaml
openshift-dev-spaces/instance/base/namespace.yaml
openshift-dev-spaces/instance/overlays/default/kustomization.yaml
openshift-dev-spaces/operator/README.md
openshift-dev-spaces/operator/base/kustomization.yaml
openshift-dev-spaces/operator/base/subscription.yaml
openshift-dev-spaces/operator/overlays/stable/kustomization.yaml

Added required manifests for the dev workspaces (previously crw) operator

Added dev workspaces operator

---

openshift-pipelines-operator/README.md
openshift-pipelines-operator/overlays/pipelines-1.7/README.md
openshift-pipelines-operator/overlays/pipelines-1.7/kustomization.yaml
openshift-pipelines-operator/overlays/pipelines-1.7/patch-channel.yaml

Add new openshift-pipelines-operator channel: 
- pipelines-1.7

Add pipelines-1.7 channel to openshift-pipelines-operator

---

submariner-operator/README.md

Noticed a small typo I made from basing the read me from the logging one

Fixed typo

---

openshift-gitops-operator/README.md
openshift-gitops-operator/overlays/gitops-1.6/README.md
openshift-gitops-operator/overlays/gitops-1.6/kustomization.yaml
openshift-gitops-operator/overlays/gitops-1.6/patch-channel.yaml

Added gitops 1.6 channel.

---

container-security-operator/overlays/stable-3.7/kustomization.yaml

Update the container security operator to 3.7

Update to CSO to 3.7

---

cert-manager-operator/operator/base/kustomization.yaml
oauth/overlays/ldap/oauth-ldap-patch.yaml
openshift-container-storage-noobaa/base/backingstore.yaml
openshift-nfd-operator/instance/base/node-feature-discovery.yaml
openshift-nfd-operator/operator/overlays/stable/kustomization.yaml

Remove unnecessary trailing spaces from objects

yamllint fix remove trailing space

---

advanced-cluster-security-operator/operator/base/namespace.yaml
advanced-cluster-security-operator/operator/base/operatorgroup.yaml
gatekeeper-operator/base/operator/kustomization.yaml
openshift-image-registry/base/image-registry-config.yaml
openshift-image-registry/base/image-registry-pvc.yaml
openshift-image-registry/base/kustomization.yaml
openshift-image-registry/overlays/vsphere/kustomization.yaml

yamllint remove extra empty lines

---

openshift-pipelines-operator/README.md
openshift-pipelines-operator/overlays/pipelines-1.8/README.md
openshift-pipelines-operator/overlays/pipelines-1.8/kustomization.yaml
openshift-pipelines-operator/overlays/pipelines-1.8/patch-channel.yaml

Add overlay for OpenShift Pipelines v1.8

Add support for OpenShift Pipelines v1.8

---

sealed-secrets-operator/base/kustomization.yaml
sealed-secrets-operator/overlays/default/kustomization.yaml
sealed-secrets-operator/overlays/default/sealed-secrets-namespace.yaml

Update sealed secrets to latest version

Sealed Secrets update

---

topology-aware-lifecycle-manager-operator/README.md
topology-aware-lifecycle-manager-operator/base/kustomization.yaml
topology-aware-lifecycle-manager-operator/base/talm-subscription.yaml
topology-aware-lifecycle-manager-operator/overlays/stable/kustomization.yaml
topology-aware-lifecycle-manager-operator/overlays/stable/patch-channel.yaml

Adds the Topology Aware Lifecycle Manager to the catalog.  First time contributor, I've tried to mimic this PR in the ways I see other similar Operators presently in the catalog.  Please let me know if I've missed something.  Thank you.

add TALM operator to the catalog

---

.wordlist-md

Resolve spelling warnings on github action

add words to spelling list

---

ansible-automation-platform/operator/README.md
ansible-automation-platform/operator/overlays/stable-2.3-cluster-scoped/kustomization.yaml
ansible-automation-platform/operator/overlays/stable-2.3-cluster-scoped/patch-channel.yaml
ansible-automation-platform/operator/overlays/stable-2.3/kustomization.yaml
ansible-automation-platform/operator/overlays/stable-2.3/patch-channel.yaml

Add new 2.3 channel for AAP since it is now out.

Add AAP 2.3

---

openshift-sriov-network-operator/README.md
openshift-sriov-network-operator/base/defaultoperatorconfig.yaml
openshift-sriov-network-operator/base/kustomization.yaml
openshift-sriov-network-operator/base/namespace.yaml
openshift-sriov-network-operator/base/operatorgroup.yaml
openshift-sriov-network-operator/base/subscription.yaml
openshift-sriov-network-operator/overlays/4.10/kustomization.yaml
openshift-sriov-network-operator/overlays/4.11/kustomization.yaml
openshift-sriov-network-operator/overlays/4.9/kustomization.yaml

Proposal to add the openshift sriov network operator to the catalog. Since I'm first time contributor please let me know if I've missed something in the process. Thank you.

add openshift-sriov-network-operator to catalog

---

jaeger-operator/base/jaeger-subscription.yaml
jaeger-operator/base/kustomization.yaml
jaeger-operator/base/operatorgroup.yaml

change default namespace as per recommendation from operator and add the appropriate operatorgroup

change default namespace as per recommendation from operator

---

.wordlist-md
jaeger-operator/base/operatorgroup.yaml
openshift-data-foundation-operator/instance/overlays/aws/storagecluster.yaml
openshift-data-foundation-operator/instance/overlays/vsphere/storagecluster.yaml

Updating wordlist and cleaning up yaml comments that break linting.

Updating wordlist and cleaning up yaml comments that break linting.

---

rhsso/operator/overlays/stable/kustomization.yaml

Add stable channel overlay for rhsso operator

Add stable overlay for rhsso operator

---

openshift-gitops-operator/README.md
openshift-gitops-operator/overlays/gitops-1.7/README.md
openshift-gitops-operator/overlays/gitops-1.7/kustomization.yaml
openshift-gitops-operator/overlays/gitops-1.7/patch-channel.yaml

Add overlay for _gitops-1.7_ channel

Add OpenShift GitOps 1.7 channel

---

openshift-pipelines-operator/README.md
openshift-pipelines-operator/overlays/pipelines-1.9/README.md
openshift-pipelines-operator/overlays/pipelines-1.9/kustomization.yaml
openshift-pipelines-operator/overlays/pipelines-1.9/patch-channel.yaml

Add _pipelines-1.9_ channel for the OpenShift Pipelines operator

Add pipelines-1.9 channel

---

.wordlist-md

Updated wordlist with "VolSync".

Updated wordlist with VolSync

---

volsync/README.md

Minor fix to pass spelling lint

Volsync to VolSync

---

openshift-sriov-network-operator/README.md
openshift-sriov-network-operator/overlays/4.12/kustomization.yaml

Adding overlay to support OpenShift SRIOV network operator in OCP 4.12

add OpenShift SRIOV network operator 4.12

---

openshift-data-foundation-operator/operator/overlays/stable-4.11/README.md
openshift-data-foundation-operator/operator/overlays/stable-4.11/kustomization.yaml
openshift-data-foundation-operator/operator/overlays/stable-4.11/patch-channel.yaml
openshift-data-foundation-operator/operator/overlays/stable-4.12/README.md
openshift-data-foundation-operator/operator/overlays/stable-4.12/kustomization.yaml
openshift-data-foundation-operator/operator/overlays/stable-4.12/patch-channel.yaml

Add 2 most current ODF operator releases.

Add ODF 4.11 & 4.12 overlays

---

quay-registry-operator/README.md
quay-registry-operator/operator/overlays/stable-3.7/README.md
quay-registry-operator/operator/overlays/stable-3.7/kustomization.yaml
quay-registry-operator/operator/overlays/stable-3.7/patch-channel.yaml
quay-registry-operator/operator/overlays/stable-3.8/README.md
quay-registry-operator/operator/overlays/stable-3.8/kustomization.yaml
quay-registry-operator/operator/overlays/stable-3.8/patch-channel.yaml

- Added 3.7 and 3.8 Quay operator channels.
- Updated README with standard usage info.

Added channels for quay operator.

---

openshift-gitops-operator/README.md
openshift-gitops-operator/operator/overlays/gitops-1.8/README.md
openshift-gitops-operator/operator/overlays/gitops-1.8/kustomization.yaml
openshift-gitops-operator/operator/overlays/gitops-1.8/patch-channel.yaml

Add OpenShift GitOps 1.8 channel.

Add OpenShift GitOps 1.8 channel.

---

advanced-cluster-management/README.md
advanced-cluster-management/operator/overlays/release-2.8/kustomization.yaml
advanced-cluster-management/operator/overlays/release-2.8/patch-channel.yaml

Added overlay for RHACM 2.8 operator.

Added ACM 2.8 operator overlay.

---

group-sync-operator/README.md
group-sync-operator/base/kustomization.yaml
group-sync-operator/base/namespace.yaml
group-sync-operator/base/operator-group.yaml
group-sync-operator/base/subscription.yaml
group-sync-operator/overlays/README.md
group-sync-operator/overlays/alpha/kustomization.yaml

Added Group Sync Operator

---

CODEOWNER

Adding a codeowners file to setup automatic reviewers for PRs

add codeowners

---

compliance-operator/operator/overlays/README.md
compliance-operator/operator/overlays/stable/kustomization.yaml

Add `stable channel` for openshift compliance operator

Add stable channel for openshift-compliance

---

openshift-data-foundation-operator/README.md
openshift-data-foundation-operator/operator/overlays/stable-4.13/README.md
openshift-data-foundation-operator/operator/overlays/stable-4.13/kustomization.yaml
openshift-data-foundation-operator/operator/overlays/stable-4.13/patch-channel.yaml

Add overlay for ODF 4.13 operator installation.

add odf 4.13 operator

---

.wordlist-md
service-interconnect-operator/README.md
service-interconnect-operator/operator/base/kustomization.yaml
service-interconnect-operator/operator/base/subscription.yaml
service-interconnect-operator/operator/overlays/alpha/kustomization.yaml

Added RHSI (Skupper) operator.

Add Red Hat Service Interconnect operator.

---

openshift-gitops-operator/INFO.md
openshift-gitops-operator/instance/base/openshift-gitops.yaml
openshift-gitops-operator/instance/components/annotation-resource-tracking/patch-resource-tracking.yaml
openshift-gitops-operator/instance/components/edge-termination/patch-edge-termination.yaml
openshift-gitops-operator/instance/components/enable-notifications/patch-enable-notifications.yaml
openshift-gitops-operator/instance/components/gitops-admins/patch-rbac.yaml
openshift-gitops-operator/instance/components/kustomize-build-enable-helm/patch-enable-helm.yaml

update argocd from v1alpha1 to v1beta1

---

advanced-cluster-management/README.md
advanced-cluster-management/operator/overlays/release-2.9/kustomization.yaml
advanced-cluster-management/operator/overlays/release-2.9/patch-channel.yaml

* Add 2.9 channel overlay
* Reverse sort the list of channel overlays in readme

add ACM 2.9 operator overlay

---

kyverno/base/kustomization.yaml

Update Kyverno to 1.11.0

---

quay-operator/operator/overlays/stable-3.10/kustomization.yaml
quay-operator/operator/overlays/stable-3.10/patch-channel.yaml
quay-operator/operator/overlays/stable-3.11/kustomization.yaml
quay-operator/operator/overlays/stable-3.11/patch-channel.yaml
quay-operator/operator/overlays/stable-3.9/kustomization.yaml
quay-operator/operator/overlays/stable-3.9/patch-channel.yaml

Adding channels for newer releases of Quay 3.9, 3.10 and 3.11.

Adding channels for 3.9, 3.10 and 3.11

---

openshift-gitops-operator/instance/components/enable-status-badge/kustomization.yaml
openshift-gitops-operator/instance/components/enable-status-badge/patch-enable-status-badge.yaml
openshift-gitops-operator/instance/overlays/default/kustomization.yaml
openshift-gitops-operator/instance/overlays/rhdp/kustomization.yaml

Adding component to enable the status badge in ArgoCD for applications.

add component to enable status badge

---

openshift-data-foundation-operator/README.md
openshift-data-foundation-operator/operator/overlays/stable-4.15/README.md
openshift-data-foundation-operator/operator/overlays/stable-4.15/kustomization.yaml
openshift-data-foundation-operator/operator/overlays/stable-4.15/patch-channel.yaml

Simple update for the ODF operators overlay: stable-4.15.

adding/updating odf overlays for stable-4.15

---

advanced-cluster-management/README.md
advanced-cluster-management/operator/overlays/release-2.10/kustomization.yaml
advanced-cluster-management/operator/overlays/release-2.10/patch-channel.yaml

Updating for the 2.10 ACM release.

Updating with 2.10 release

---

.wordlist-md
1password-connect/README.md

Fix some spelling issues in the linting

fix spelling issues

---

openshift-data-foundation-operator/README.md
openshift-data-foundation-operator/operator/overlays/stable-4.16/README.md
openshift-data-foundation-operator/operator/overlays/stable-4.16/kustomization.yaml
openshift-data-foundation-operator/operator/overlays/stable-4.16/patch-channel.yaml

add odf overlay for stable-4.16

---

.github/workflows/validate-manifests.yaml

Adding back in the yaml lint action that was accidently deleted in #317

add back in yaml lint

---

openshift-gitops-operator/README.md
openshift-gitops-operator/operator/overlays/gitops-1.13/kustomization.yaml
openshift-gitops-operator/operator/overlays/gitops-1.13/patch-subscription.yaml

Added 1.13 overlay for OpenShift GitOps operator.

Add OpenShift GitOps 1.13 overlay

---

scripts/validate_kustomize.sh

This pull request changes validate_kustomize.sh in the following ways:
1. Don't error when helm isn't installed; instead, just skip kustomizations that use helm
2. Don't error when components fail kustomize build, because it is valid to have a component that references resources not directly included within the component.

validate_kustomize.sh fixes: missing helm and partial kustomize components

---

ansible-automation-platform/operator/overlays/stable-2.5-cluster-scoped/kustomization.yaml
ansible-automation-platform/operator/overlays/stable-2.5-cluster-scoped/patch-channel.yaml
ansible-automation-platform/operator/overlays/stable-2.5/kustomization.yaml
ansible-automation-platform/operator/overlays/stable-2.5/patch-channel.yaml

This pull requests adds overlays for AAP operator channels stable-2.5 and stable-2.5-cluster-scoped

Add AAP 2.5 overlays

---

openshift-data-foundation-operator/README.md
openshift-data-foundation-operator/operator/overlays/stable-4.17/README.md
openshift-data-foundation-operator/operator/overlays/stable-4.17/kustomization.yaml
openshift-data-foundation-operator/operator/overlays/stable-4.17/patch-channel.yaml

add openshift data foundation operator overlay for stable-4.17

add odf overlay for stable-4.17

---

container-security-operator/README.md
container-security-operator/overlays/stable-3.13/kustomization.yaml

Add stable-3.13 channel to container-security

Add stable-3.13 channel to container-security

---

nmstate/instance/base/nmstate-nmstate.yaml

Fixes #290 
* replace nmstate.io/v1beta1 with v1
* replace nodeselector with empty spec

update nmstate api ver

---

.wordlist-md
zero-trust-workload-identity-manager/README.md
zero-trust-workload-identity-manager/aggregate/default/kustomization.yaml
zero-trust-workload-identity-manager/instance/base/SpiffeCSIDriver.yaml
zero-trust-workload-identity-manager/instance/base/SpireAgent.yaml
zero-trust-workload-identity-manager/instance/base/SpireOIDCDiscoveryProvider.yaml
zero-trust-workload-identity-manager/instance/base/SpireServer.yaml
zero-trust-workload-identity-manager/instance/base/kustomization.yaml
zero-trust-workload-identity-manager/instance/overlays/default/kustomization.yaml
zero-trust-workload-identity-manager/operator/base/kustomization.yaml
zero-trust-workload-identity-manager/operator/base/namespace.yaml
zero-trust-workload-identity-manager/operator/base/operator-group.yaml
zero-trust-workload-identity-manager/operator/base/subscription.yaml
zero-trust-workload-identity-manager/operator/overlays/tech-preview/kustomization.yaml

Added Zero Trust Workload Identity Manager

Added Zero Trust Workload Identity Manager

---

advanced-cluster-management/README.md
advanced-cluster-management/operator/overlays/release-2.13/kustomization.yaml
advanced-cluster-management/operator/overlays/release-2.13/patch-channel.yaml
advanced-cluster-management/operator/overlays/release-2.14/kustomization.yaml
advanced-cluster-management/operator/overlays/release-2.14/patch-channel.yaml
gpu-operator-certified/README.md
gpu-operator-certified/operator/overlays/v23.9/kustomization.yaml
gpu-operator-certified/operator/overlays/v23.9/patch-channel.yaml
gpu-operator-certified/operator/overlays/v24.9/kustomization.yaml
gpu-operator-certified/operator/overlays/v24.9/patch-channel.yaml
gpu-operator-certified/operator/overlays/v25.3/kustomization.yaml
gpu-operator-certified/operator/overlays/v25.3/patch-channel.yaml
openshift-data-foundation-operator/README.md
openshift-data-foundation-operator/operator/overlays/stable-4.19/README.md
openshift-data-foundation-operator/operator/overlays/stable-4.19/kustomization.yaml
openshift-data-foundation-operator/operator/overlays/stable-4.19/patch-channel.yaml

_Addresses a very well articulated issue_ #377

Update ACM, GPU, and ODF operators

---

nfd/instance/base/node-feature-discovery.yaml
nfd/instance/overlays/kata/nfd.yaml
nfd/instance/overlays/only-nvidia/patch-node-feature-discovery.yaml

Addressing this issue: https://github.com/redhat-cop/gitops-catalog/issues/376

Nfd fix config

---

zero-trust-workload-identity-manager/README.md
zero-trust-workload-identity-manager/instance/base/SpireOIDCDiscoveryProvider.yaml
zero-trust-workload-identity-manager/instance/base/SpireServer.yaml
zero-trust-workload-identity-manager/instance/overlays/default/kustomization.yaml
zero-trust-workload-identity-manager/operator/overlays/tech-preview/kustomization.yaml

Support for Zero Trust Workload Identity Manager TP 2.0

ZTWIM TP 2.0
