installplan-approver/base/installplan-approver-job.yaml

There is a bug in OLM that generates two installPlans and you need to approve the one that is refeerenced in the subscription. I simplified your approver to work off the installplan status field in the subscription to do this instead of driving off a desiredCSV. There are possibility some edge cases I missed so have a look.

Fix approver job when there are multiple installplans due to OLM bug

---

sealed-secrets-operator/base/bitnami-sealed-secrets.yaml

Add support for status field in sealed-secrets. This makes it much easier to understand the status of the secret plus can be used by ArgoCD to fail sealed-secrets that failed.

Enable status support in sealed secrets

---

grafana-operator/base/instance/grafana.yaml

Enable grafana authorization to be configurable by moving sar into an environment variable. See here for more details on oauth-proxy and subject access review (sar).
https://github.com/openshift/oauth-proxy#limiting-access-to-users

Make authz configurable by moving sar to env variable

---

letsencrypt-certs/base/job-serviceaccount.yaml

Testing the letsencrypt-certs kustomization, I received an error:
```
oc apply -k letsencrypt-certs/base
error: rawResources failed to read Resources: id '"batch_v1_Job|letsencrypt-job|~P|letsencrypt-certificates-job|~S"' already used
```
I check the job.yaml and the job-serviceaccount.yaml and are the same file, I suppose that this is a wrong file. Instead I changed the SA for the proper one referred in the @pittar personal ocp-letsencrypt-job repo.
After testing worked like a charm:
```
oc apply -k letsencrypt-certs/base
namespace/letsencrypt-job unchanged
serviceaccount/letsencrypt-job-sa created
clusterrole.rbac.authorization.k8s.io/letsencrypt-certs-clusterrole unchanged
clusterrole.rbac.authorization.k8s.io/letsencrypt-ingresscontroller-clusterrole unchanged …
```

substitute the content of the SA with the proper definition instead of job.yaml

---

installplan-approver/README.md
installplan-approver/base/installplan-approver-job.yaml

There is a name conflict for `subscriptions` between operators and knative:
subscriptions.messaging.knative.dev
subscriptions.operators.coreos.com 
This update makes the `oc get subscription` more specific if the cluster has knative installed on it.
I also added some usage docs because why not.

Installplan subscription fix

---

jaeger-operator/base/kustomization.yaml
jaeger-operator/overlays/1.17-stable/README.md
jaeger-operator/overlays/1.17-stable/kustomization.yaml
jaeger-operator/overlays/1.17-stable/patch-channel-and-version.yaml
jaeger-operator/overlays/1.20-stable/README.md
jaeger-operator/overlays/1.20-stable/kustomization.yaml
jaeger-operator/overlays/1.20-stable/patch-channel-and-version.yaml
jaeger-operator/overlays/README.md
jaeger-operator/overlays/stable/README.md
jaeger-operator/overlays/stable/kustomization.yaml
jaeger-operator/overlays/stable/patch-channel-and-version.yaml
jaeger-operator/overlays/tech-preview/README.md
jaeger-operator/overlays/tech-preview/kustomization.yaml
jaeger-operator/overlays/tech-preview/patch-channel-and-version.yaml

Some additional updates that I would like to add to keep things more consistent with other folders but would possibly break if someone referenced the jaeger install from another repo:
- rename `jaeger-operator` -> `openshift-jaeger-operator`
- delete `jaeger-operator\overlays\default`
- update `jaeger-operator\base\jaeger-subscription.yaml` to use `patch-me-see-overlays-dir` for `channel` and `startingCSV`
Any thoughts making those updates?

Update jaeger operator overlays

---

elastisearch-operator/README.md
elastisearch-operator/base/kustomization.yaml
elastisearch-operator/overlays/4.6/README.md
elastisearch-operator/overlays/4.6/kustomization.yaml
elastisearch-operator/overlays/4.6/patch-channel-and-version.yaml
elastisearch-operator/overlays/5.0/README.md
elastisearch-operator/overlays/5.0/kustomization.yaml
elastisearch-operator/overlays/5.0/patch-channel-and-version.yaml
elastisearch-operator/overlays/stable/README.md
elastisearch-operator/overlays/stable/kustomization.yaml
elastisearch-operator/overlays/stable/patch-channel-and-version.yaml

Some additional updates that I would like to make to align this with the rest of the catalog but would introduce some breaking changes if someone is referencing the repo:
- rename `elastisearch-operator` -> `openshift-elastisearch-operator`
- update `elastisearch-operator\base\elastisearch-subscription.yaml` to use `patch-me-see-overlays-dir` for `channel` and `startingCSV`
Let me know if you think those changes would be worth it!

update elastisearch overlays

---

sealed-secrets-operator/README.md

Kustomize fails to build the manifest as the folder within the `catalog` git repo is `sealed-secrets-operator` and not `sealed-secrets`
That commit changed the folder name: https://github.com/redhat-canada-gitops/catalog/commit/74ab574caf82562ba64bec1e886012f1e593b97f
Error
`Error: accumulating resources: accumulation err='accumulating resources from 'github.com/redhat-canada-gitops/catalog/sealed-secrets/overlays/default?ref=master': evalsymlink failure on '/Users/adetalhouet/tmp/ocp-gitops/apps/00-sealed-secrets/github.com/redhat-canada-gitops/catalog/sealed-secrets/overlays/default?ref=master' : lstat /Users/adetalhouet/tmp/ocp-gitops/apps/00-sealed-secrets/github.com: no such file or directory': evalsymlink failure on '/private/var/folders/p0/7r6t73s915536ksg4s9l_kwr0000gn/T/kustomize- …

Fix sealed-secrets-operator base url

---

README.md
amq-streams-operator/README.md
elastisearch-operator/README.md
installplan-approver/README.md
jaeger-operator/overlays/README.md
kiali-operator/README.md
letsencrypt-certs/README.md
namespace-configuration-operator/README.md
opendatahub-operator/README.md
openshift-container-storage-noobaa/README.md
openshift-container-storage-operator/README.md
openshift-gitops-operator/README.md
openshift-pipelines-operator/README.md
openshift-pipelines-tasks/dotnet/README.md
openshift-serverless-knative-eventing/README.md
openshift-serverless-knative-serving/README.md
openshift-serverless-operator/README.md
openshift-servicemesh/instance/README.md
openshift-servicemesh/operator/README.md

First pass at updating docs to reference `redhat-cop/gitops-catalg` instead of `redhat-canada-gitops/catalog`.

First pass at updating docs for redhat-cop refs.

---

openshift-pipelines-tasks/maven/base/maven-task.yaml

Change the maven's default task from a google image to a Red Hat one that is included in OpenShift

Change default image to a RH image

---

nexus2/base/configure-nexus-job.yaml
sonarqube8/overlays/plugins/configure-sonarqube-job.yaml

Replace existing Nexus and Sonarqube script URLs that point to Red Hat Canada with new Red Hat CoP links

Update Nexus and Sonarqube script URLs

---

elastisearch-operator/base/elasticsearch-operatorgroup.yaml
elastisearch-operator/base/elastisearch-subscription.yaml
elastisearch-operator/base/kustomization.yaml
elastisearch-operator/base/namespace.yaml

Fix for https://github.com/redhat-cop/gitops-catalog/issues/54 .  Added `openshift-operators-redhat` namespace and updated base/overlays where required.

Fix for issue 54.

---

sealed-secrets-operator/overlays/update-status/kustomization.yaml
sealed-secrets-operator/overlays/update-status/patch-sealed-secrets.yaml

Sealed Secret Resources will not show up healthy on ArgoCD starting with 2.0 and SealedSecret 0.16 unless you run the controller with --update-status to create a status block in SealedSecret resources.
I created a new overlay to support this use case
Ref:
https://argoproj.github.io/argo-cd/faq/#why-are-sealedsecret-resources-reporting-a-status
https://github.com/bitnami-labs/sealed-secrets/issues/555
https://github.com/bitnami-labs/sealed-secrets/blob/main/RELEASE-NOTES.md#v0150

Add Sealed Secret Overlay to run controller with update status

---

installplan-approver/base/installplan-approver-job.yaml

Currently it is not possible to customize the Job because of an empty line here: https://github.com/redhat-cop/gitops-catalog/blob/e111499127d07bc11d54f494e121c2e901b9482e/installplan-approver/base/installplan-approver-job.yaml#L14
Error:
`error: yaml: line 31: mapping values are not allowed in this context`
<p>&nbsp;</p>
Deleting this empty line allows for example to rename the job with Kustomize:
```
example-customize-installplan-approver/
├── base/
│   └── kustomization.yaml
├── overlays/
│   └── production/
│       ├── patch-name-install-plan.yaml
│       └── kustomization.yaml
```
`base/kustomization.yaml`:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- github.com/redhat-cop/gitops-catalog/installplan-approver/base?ref=main
``` …

Allow customization of installpan-approver Job

---

ansible-automation-platform/instance/overlays/default/kustomization.yaml

fixes #94 per @pittar request to remove the customization of URL

Removed renaming of the URL for Ansible Automation Platform Operator

---

installplan-approver/base/installplan-approver-job.yaml

Instead of approving just the installplan of the first element in the subscription array, you should iterate over all elements
(.items[0].metadata.name vs. .items[*].metadata.name)

iterate over all subscriptions in a namespace

---

oauth/README.md
oauth/overlays/htpass/files/users.htpasswd
oauth/overlays/htpass/kustomization.yaml

This is an updated to the current htpass overlay in oauth.
The kustomization now generates the secret using the secretGenerator based on the users.htpasswd found in the files directory.
The users.htpasswd file contains a single user admin with password redhat.
The README file was created to start documenting the providers.
The existent htpass-secret.yaml is not used and can be removed.

Change the oauth/htpass overlay to use secretGenerator

---

sealed-secrets-operator/README.md

Remove redundant "catalog" word in the kustomization file example
fix #120

Fix sealed secrets example url

---

oauth/README.md

The README file showed a different password from the actual password in the user.htpasswd file for htpass. This has been fixed in case someone wishes to use the overlay without changes for testing purposes.

Fix the README of the oauth to show the default password for htpass

---

openshift-image-registry/README.md
openshift-image-registry/base/image-registry-config.yaml
openshift-image-registry/base/image-registry-pvc.yaml
openshift-image-registry/base/kustomization.yaml
openshift-image-registry/overlays/vsphere/kustomization.yaml

Enable the internal image registry to work on vSphere with a simple PVC from the default block storage.

Add openshift-image-registry for vsphere with vmdk

---

cert-manager-operator/README.md
cert-manager-operator/examples/acs-central-certificate/README.md
cert-manager-operator/examples/acs-central-certificate/acs-central-certificate.yaml
cert-manager-operator/examples/acs-central-certificate/kustomization.yaml
cert-manager-operator/examples/letsencrypt-route53-issuer/README.md
cert-manager-operator/examples/letsencrypt-route53-issuer/kustomization.yaml
cert-manager-operator/examples/letsencrypt-route53-issuer/letsencrypt-prod-cluster-issuer.yaml
cert-manager-operator/examples/letsencrypt-route53-issuer/letsencrypt-staging-cluster-issuer.yaml
cert-manager-operator/examples/openshift-api-certificate/README.md
cert-manager-operator/examples/openshift-api-certificate/kustomization.yaml
cert-manager-operator/examples/openshift-api-certificate/openshift-api-certificate.yaml
cert-manager-operator/examples/openshift-api-certificate/patch-cluster-api-cert-job.yaml
cert-manager-operator/examples/openshift-wildcard-certificate/README.md
cert-manager-operator/examples/openshift-wildcard-certificate/kustomization.yaml
cert-manager-operator/examples/openshift-wildcard-certificate/openshift-wildcard-certificate.yaml
cert-manager-operator/examples/openshift-wildcard-certificate/patch-cluster-wildcard-cert-job.yaml
cert-manager-operator/operator/base/kustomization.yaml
cert-manager-operator/operator/base/operator-group.yaml
cert-manager-operator/operator/base/operator-namespace.yaml
cert-manager-operator/operator/base/subscription.yaml

This PR adds support for the new Red Hat cert-manager operator that is in Tech Preview in 4.10. It also includes some examples of how to use it from a GitOps perspective to generate certs for OpenShift API and wildcard endpoints as well as for ACS.

Add cert-manager to the repository

---

advanced-cluster-management/operator/README.md
ansible-automation-platform/operator/README.md
business-automation-operator/operator/README.md
container-security-operator/README.md
elasticsearch-operator/README.md
gatekeeper-operator/README.md
jaeger-operator/overlays/README.md
kiali-operator/README.md
opendatahub-operator/README.md
openshift-container-storage-noobaa/README.md
openshift-container-storage-operator/README.md
openshift-data-foundation-operator/README.md
openshift-gitops-operator/README.md
openshift-logging/operator/README.md
openshift-pipelines-operator/README.md
openshift-serverless/instance/knative-eventing/README.md
openshift-serverless/instance/knative-serving/README.md
openshift-serverless/operator/README.md
openshift-servicemesh/instance/README.md
openshift-servicemesh/operator/README.md
quay-registry-operator/README.md
rhsso/operator/README.md
seldon-operator/operator/README.md

The docs reference the patches for `channel` and `version` for operator subscriptions.  Since all of the `startingCSV` objects in Subscriptions have been removed there is no need for the docs to reference patching the version.

remove references to startingCSV from docs

---

openshift-data-foundation-operator/aggregate/overlays/aws-node-labeler/kustomization.yaml
openshift-data-foundation-operator/aggregate/overlays/aws/kustomization.yaml
openshift-data-foundation-operator/config-helpers/README.md
openshift-data-foundation-operator/config-helpers/node-labeler/base/kustomization.yaml
openshift-data-foundation-operator/config-helpers/node-labeler/base/node-label-job.yaml
openshift-data-foundation-operator/config-helpers/node-labeler/base/rbac.yaml
openshift-data-foundation-operator/config-helpers/node-labeler/base/service-account.yaml
openshift-data-foundation-operator/config-helpers/node-labeler/overlays/default/kustomization.yaml
openshift-data-foundation-operator/instance/README.md
openshift-data-foundation-operator/instance/base/kustomization.yaml
openshift-data-foundation-operator/instance/base/storagesystem.yaml
openshift-data-foundation-operator/instance/overlays/aws/kustomization.yaml
openshift-data-foundation-operator/instance/overlays/aws/ocsinitialization.yaml
openshift-data-foundation-operator/instance/overlays/aws/storagecluster.yaml

Created an example instance of ODF intended to work with AWS (tested on RHPDS).
Additionally created a `config-helpers` folder that contains a job to help label the worker nodes.  I went back and forth on if this should be included in the `aws` overlay or a separate `aws-node-labeler` overlay and ultimately settled on creating the `config-helpers` folder.  The node-labeler should work with any future instance overlays and keeping it in the `config-helpers` will prevent the files from having to be copied to multiple instances in the future.  I also didn't want to include in the in the base because it may not be wanted for some ODF deployments where other methods are being used for labeling the nodes.
Since this folder is a new pattern in the gitops-catalog I welcome any feedback!

add odf instance example

---

openshift-data-foundation-operator/operator/base/enable-console-plugin-job.yaml
openshift-data-foundation-operator/operator/base/enable-console-plugin-rbac.yaml
openshift-data-foundation-operator/operator/base/enable-console-plugin-sa.yaml
openshift-data-foundation-operator/operator/base/kustomization.yaml

This is a follow up to #133 
I noticed today that simply adding the console plugin object is not enough and you have to add the plugin to the consoles object as well.
This update creates a job that patches the consoles object.  The job will check to see if the plugin is already listed in the object and if it isn't, the plugin is added to the list.
I'm not crazy about doing it this with a job but I didn't want to bring the console object into this operator base since other operators may also need to add to the list of plugins in the future.
If there is another simple way to handle a patch like this please let me know.

add job to enable odf plugin

---

openshift-pipelines-operator/overlays/latest/README.md
openshift-pipelines-operator/overlays/latest/kustomization.yaml
openshift-pipelines-operator/overlays/latest/patch-channel.yaml
openshift-pipelines-operator/overlays/stable/README.md

Pipelines operator now uses latest channel to track newest releases instead of stable. This PR adds the latest channel and deprecates (but not removes) stable.
Longer term we should also create overlays for per version channels that are now available.

Add latest channel, deprecate stable

---

oauth/overlays/htpass/cluster-admin-role.yaml
oauth/overlays/htpass/kustomization.yaml

I have added a `ClusterRoleBinding` resource to grant cluster-admin to the user `admin` created in the htpass overlay.
This is to get a proper admin account without having to execute additional commands.

Add cluster role to new admin user

---

advanced-cluster-security-operator/operator/base/kustomization.yaml
advanced-cluster-security-operator/operator/base/namespace.yaml
advanced-cluster-security-operator/operator/base/operatorgroup.yaml
advanced-cluster-security-operator/operator/base/subscription.yaml
advanced-cluster-security-operator/operator/overlays/latest/kustomization.yaml

The official documentation suggests using the namespace rhacs-operator to install the RHACS Operator.
The new namespace and operator group resources were created and the subscription pointed to that namespace. Now the RHACS is installed on rhacs-operator instead of openshift-operators.

Add namespace for the rhacs operator

---

external-secrets-operator/operator/overlays/README.md
external-secrets-operator/operator/overlays/stable/kustomization.yaml

Add new external secrets operator channel:
- stable
It can also be seen here:
https://operatorhub.io/operator/external-secrets-operator/stable/external-secrets-operator.v0.5.9

 Add stable channel to external secrets operator

---

elasticsearch-operator/README.md
elasticsearch-operator/overlays/stable-5.1/README.md
elasticsearch-operator/overlays/stable-5.1/kustomization.yaml
elasticsearch-operator/overlays/stable-5.1/patch-channel.yaml
elasticsearch-operator/overlays/stable-5.2/README.md
elasticsearch-operator/overlays/stable-5.2/kustomization.yaml
elasticsearch-operator/overlays/stable-5.2/patch-channel.yaml
elasticsearch-operator/overlays/stable-5.3/README.md
elasticsearch-operator/overlays/stable-5.3/kustomization.yaml
elasticsearch-operator/overlays/stable-5.3/patch-channel.yaml
elasticsearch-operator/overlays/stable-5.4/README.md
elasticsearch-operator/overlays/stable-5.4/kustomization.yaml
elasticsearch-operator/overlays/stable-5.4/patch-channel.yaml
elasticsearch-operator/overlays/stable-5.5/README.md
elasticsearch-operator/overlays/stable-5.5/kustomization.yaml
elasticsearch-operator/overlays/stable-5.5/patch-channel.yaml
elasticsearch-operator/overlays/stable/README.md

Add new stable-5-x (5.1 to 5.5) channels for the elasticsearch operator
It covers OCP 4.7 until OCP 4.11.
Reference:
https://docs.openshift.com/container-platform/4.11/logging/cluster-logging-deploying.html#cluster-logging-deploy-cli_cluster-logging-deploying

Add elasticsearch-operator channels

---

openshift-data-foundation-operator/README.md
openshift-data-foundation-operator/aggregate/overlays/vsphere-node-labeler/kustomization.yaml
openshift-data-foundation-operator/aggregate/overlays/vsphere/kustomization.yaml
openshift-data-foundation-operator/instance/README.md
openshift-data-foundation-operator/instance/overlays/vsphere/kustomization.yaml
openshift-data-foundation-operator/instance/overlays/vsphere/ocsinitialization.yaml
openshift-data-foundation-operator/instance/overlays/vsphere/storagecluster.yaml

Adds new vSphere overlays to the OpenShift Data Foundation Operator with `thin` storage and flexible scaling enabled, as vSphere clusters don't have zones/racks by default.

Add vsphere overlays to openshift-data-foundation-operator

---

.github/workflows/kustomize-lint.yaml

Closes #62 
Add GitHub action to run yamllint to enforce yaml standards.
Yamllint action includes ability to annotate format issues automatically.
Example of bad commit:
https://github.com/strangiato/gitops-catalog/actions/runs/2952926756

Add yamllint action

---

openshift-data-foundation-operator/instance/overlays/aws/storagecluster.yaml
openshift-data-foundation-operator/instance/overlays/vsphere/storagecluster.yaml

Version is currently hardcoded into the instance examples.  If the version is not included in the object ODF will dynamically set the version based on the operator version.

Make storagecluster version dynamic

---

sealed-secrets-operator/README.md

Remove the namespace file from the sealed secrets readme as it's already created (after #177) and Kustomize can't add a resource that is already created:
```
may not add resource with an already registered id: Namespace.v1.[noGrp]/sealed-secrets.[noNs]
```

Fix sealed secret readme

---

.github/workflows/spellcheck.yaml
.github/workflows/validate-manifests.yaml

The base checkout action has updated to v3 and v2 has been depreciated.

migrate to actions/checkout@v3

---

container-security-operator/README.md

The path `container-security-operator/operator/overlays/<channel>` does not exist, removing the `operator` directory from the path.

Fix typo in container-security-operator readme

---

openshift-sandboxed-containers/README.md
openshift-sandboxed-containers/operator/overlays/stable-1.3/kustomization.yaml
openshift-sandboxed-containers/operator/overlays/stable-1.3/openshift-sandboxed-containers-operator-sub.yaml

Add stable-1.3 channel for the openshift-sandboxed-containers
Reference:
[OpenShift 4.12 documentation](https://docs.openshift.com/container-platform/4.12/sandboxed_containers/deploying-sandboxed-container-workloads.html#deploying-sandboxed-containers-workloads-web-console)

Add stable-1.3 channel for the openshift-sandboxed-containers

---

serverless-operator/instance/knative-eventing/base/knative-eventing-instance.yaml
serverless-operator/instance/knative-serving/base/knative-serving-instance.yaml

The serving and eventing v1alpha1 APIs were depreciated in 1.27:
https://docs.openshift.com/container-platform/4.12/serverless/serverless-release-notes.html#serverless-deprecated-removed-features_serverless-release-notes
KnativeKafka is still utilizing v1alpha1 API

switch serverless apis to beta

---

cert-manager-operator/README.md
cert-manager-operator/operator/base/namespace.yaml
cert-manager-operator/operator/base/operator-group.yaml
cert-manager-operator/operator/base/subscription.yaml

* updated to use stable-v1 channel
* change manifests so that they are closer to what is deployed when doing a manual web ui based installation of the operator
https://docs.openshift.com/container-platform/4.12/security/cert_manager_operator/cert-manager-operator-install.html describes the process
Signed-off-by: Christoph Görn <goern@redhat.com>

updated to v0.10, stable-v1

---

group-sync-operator/overlays/alpha/kustomization.yaml

Remove namespace from the `kustomization.yaml` in the from Group Sync Operator alpha overlay

Remove namespace from Group Sync Operator

---

openshift-data-foundation-operator/operator/base/enable-console-plugin-job.yaml

Use the OpenShift client image from Red Hat registry rather than assuming the local cluster registry has already been deployed with an alternative storage back end.
fixes #171

remove cluster registry dependency from ODF console plugin enabler job

---

advanced-cluster-security-operator/instance/base/secured-cluster.yaml

Changed the mode of `SecuredCluster` collection to `EBPF` as `KernelModule` was deprecated

Changed ACS secured cluster collection type to EBPF

---

advanced-cluster-security-operator/README.md
advanced-cluster-security-operator/aggregate/default/kustomization.yaml
advanced-cluster-security-operator/operator/overlays/stable/kustomization.yaml

The channel name "stable" now refers to version 4.x, while "latest" is still version 3.x

Added stable channel subscription overlay

---

README.md

Looks like the badge in the readme broke that reports the status of the github actions.  This should fix the badge.

fix workflow badge in readme

---

openshift-data-foundation-operator/config-helpers/node-labeler/base/node-label-job.yaml

Use the OpenShift client image from Red Hat registry rather than assuming the local cluster registry has already been deployed with an alternative storage back end.

use openshift client image from redhat registry for node-labeler job

---

.wordlist-md
CONTRIBUTING.md
scripts/sort-wordlist.sh

Adding a script to help sort the words consistently across MacOS and RHEL.
It appears that MacOS and RHEL have a slightly different default configuration for how to handle the sort with Capitol letters so the script will work the same for both environments.
I also added a few quick notes on the contributing guide for the spell checker.

Sort wordlist script

---

.wordlist-md
eck-operator/README.md
eck-operator/base/kustomization.yaml
eck-operator/base/namespace.yaml
eck-operator/base/operatorgroup.yaml
eck-operator/base/subscription.yaml
eck-operator/overlays/stable/kustomization.yaml

Add the Elastic Cloud for Kubernetes operator and stable overlay to the catalog

Add eck-operator with stable overlay

---

ack-system/scripts/setup.sh
advanced-cluster-management/remove-acm.sh
advanced-cluster-security
scripts/automate_operators.sh
scripts/lint.sh
scripts/validate_manifests.sh

- improve: linting
- update/fix: operator generator script
- fix: ack operator script

update: scripts

---

.wordlist-md
redhat-keycloak/operator/README.md
redhat-keycloak/operator/base/kustomization.yaml
redhat-keycloak/operator/base/namespace.yaml
redhat-keycloak/operator/base/operatorgroup.yaml
redhat-keycloak/operator/base/subscription.yaml
redhat-keycloak/operator/overlays/stable-v22/kustomization.yaml

Add the Red Hat Keycloak operator and stable-v22 overlay.

Add Red Hat Keycloak operator

---

openshift-data-foundation-operator/README.md
openshift-data-foundation-operator/operator/overlays/stable-4.14/README.md
openshift-data-foundation-operator/operator/overlays/stable-4.14/kustomization.yaml
openshift-data-foundation-operator/operator/overlays/stable-4.14/patch-channel.yaml

Added channel 4.14 for ODF.
*** Tested in a lab and working. ***

Added channel 4.14 for ODF

---

.yamllint

Disable the yamllint config that checks for comment indentation to resolve warning that has been popping up on all PRs.

disable comment indentation check

---

file-integrity-operator/README.md
file-integrity-operator/operator/overlays/README.md
file-integrity-operator/operator/overlays/stable/kustomization.yaml
file-integrity-operator/operator/overlays/v1/kustomization.yaml

Added two new channels (`stable `and `v1`) for the `file integrity operator`.
Replaced the old `release-0.1` channel in the operator readme by the `stable` one.
> The File Integrity Operator is now stable and the release channel is upgraded to stable. Future releases will follow [Semantic Versioning](https://semver.org/). To access the latest release, see [Updating the File Integrity Operator](https://docs.openshift.com/container-platform/4.14/security/file_integrity_operator/file-integrity-operator-updating.html#olm-preparing-upgrade_file-integrity-operator-updating).
Reference:
[Release notes](https://docs.openshift.com/container-platform/4.14/security/file_integrity_operator/file-integrity-operator-release-notes.html)

Updating the file integrity operator

---

openshift-pipelines-operator/base/kustomization.yaml
openshift-pipelines-operator/components/README.md
openshift-pipelines-operator/components/enable-console-plugin/README.md
openshift-pipelines-operator/components/enable-console-plugin/console-plugin-job.sh
openshift-pipelines-operator/components/enable-console-plugin/console-plugin-job.yaml
openshift-pipelines-operator/components/enable-console-plugin/console-plugin.yaml
openshift-pipelines-operator/components/enable-console-plugin/kustomization.yaml

Create a new job that enables the console plugin for the OpenShift Pipelines operator.

Add console plugin job for OpenShift Pipelines

---

openshift-gitops-operator/instance/components/kustomize-build-policy-generator/README.md
openshift-gitops-operator/instance/components/kustomize-build-policy-generator/kustomization.yaml
openshift-gitops-operator/instance/components/kustomize-build-policy-generator/patch-enable-policy-generator.yaml

This adds a new component for patching the argocd instance to enable the ACM policy generator plugin.
Since this component has a conflict with the kustomize-build-enable-helm component I have added some notes on both to indicate that they are not compatible with each other.

add policy-generator component

---

lvm-storage/README.md
lvm-storage/operator/overlays/stable-4.14/kustomization.yaml
lvm-storage/operator/overlays/stable-4.14/patch-channel.yaml
lvm-storage/operator/overlays/stable-4.15/kustomization.yaml
lvm-storage/operator/overlays/stable-4.15/patch-channel.yaml

Overview:
- Simple update for LVM operators overlay to include 4.14, and 4.15. 
- Updated readme with changes, and made changes consistent with ODF readme (recent top-down).
Happy to change formatting to something else if advised. Thanks for the fast merges. :)

update overlays for lvm, and update readme

---

grafana-operator/base/instance/grafana-proxy-rbac.yaml
grafana-operator/base/instance/grafana.yaml
grafana-operator/base/instance/injected-certs-cm.yaml
grafana-operator/base/instance/kustomization.yaml
grafana-operator/base/instance/session-secret.yaml
grafana-operator/base/operator/subscription.yaml
grafana-operator/overlays/user-app-example/kustomization.yaml
grafana-operator/overlays/user-app-example/patch-cluster-monitoring-view.yaml
grafana-operator/overlays/user-app-example/patch-grafana-sar.yaml
grafana-operator/overlays/user-app/cluster-monitor-view-rb.yaml
grafana-operator/overlays/user-app/grafana-auth-secret.yaml
grafana-operator/overlays/user-app/grafana-ds.yaml
grafana-operator/overlays/user-app/kustomization.yaml

Grafana has dropped support for v4 and now the v4 channel installs v5 grafana. The CRDs between v4 and v5 have changed significantly, this PR will update grafana to work as expected on OpenShift with the V5 version.

Update Grafana for V5

---

1password-connect/README.md
1password-connect/aggregate/overlays/default/kustomization.yaml
1password-connect/connect/base/deployment.yaml
1password-connect/connect/base/kustomization.yaml
1password-connect/connect/base/namespace.yaml
1password-connect/connect/base/scc.yaml
1password-connect/connect/base/service.yaml
1password-connect/connect/base/serviceaccount.yaml
1password-connect/connect/overlays/default/kustomization.yaml
1password-connect/operator/base/clusterrole.yaml
1password-connect/operator/base/clusterrolebinding.yaml
1password-connect/operator/base/deployment.yaml
1password-connect/operator/base/kustomization.yaml
1password-connect/operator/base/rolebinding.yaml
1password-connect/operator/base/scc.yaml
1password-connect/operator/base/serviceaccount.yaml
1password-connect/operator/overlays/default/kustomization.yaml

Adds support for the 1Password Connect and Operator: https://developer.1password.com/docs/connect/

Add 1Password Connect and Operator

---

loki-operator/operator/base/kustomization.yaml
loki-operator/operator/base/namespace.yaml
loki-operator/operator/base/subscription.yaml
loki-operator/operator/overlays/stable-5.8/kustomization.yaml
loki-operator/operator/overlays/stable-5.8/patch-channel.yaml
loki-operator/operator/overlays/stable-5.9/kustomization.yaml
loki-operator/operator/overlays/stable-5.9/patch-channel.yaml
loki-operator/operator/overlays/stable/kustomization.yaml
loki-operator/operator/overlays/stable/patch-channel.yaml

This pull requests adds manifests to deploy the loki operator
fixes #308 
Based on latest official docs: https://docs.openshift.com/container-platform/4.15/observability/logging/log_storage/installing-log-storage.html#logging-loki-cli-install_installing-log-storage

Add loki operator manifests

---

advanced-cluster-management/README.md
advanced-cluster-management/operator/overlays/release-2.11/kustomization.yaml
advanced-cluster-management/operator/overlays/release-2.11/patch-channel.yaml

Add RHACM operator v2.11 overlay

add rhacm 2.11 overlay

---

openshift-gitops-operator/instance/overlays/default/gitops-admins-group.yaml

There is no reference to this file from within kustomization.yaml in its directory. Also, this file is part of `../../components/gitops-admins` component, where is the proper place for it.

Delete gitops-admins-group.yaml from default overlay directory.

---

openshift-gitops-operator/operator/components/disable-default-instance/patch-subscription.yaml

This is because of the following error while applying an overlay with `disable-default-instance` component:
`The Subscription "openshift-gitops-operator" is invalid: spec.config.env[0].value: Invalid value: "boolean": spec.config.env[0].value in body must be of type string: "boolean"`

Change env value from boolean to string

---

nfd/instance/base/node-feature-discovery.yaml

GitOps projects that use the nfd operator have been failing in OpenShift 4.17, it looks like the base image has been changed - we verified this by manually installing the operator and observing the new image name.
Update base image in node-feature-discovery.yaml fixes the issue.
We've tested this on an OpenShift 4.17 and 4.15 cluster, and NFD is now working great. More details in one of the downstream projects at: https://github.com/redhat-ai-services/ai-accelerator/pull/80

Fix for Node Feature Discovery Operator in OCP 4.17

---

service-interconnect-operator/README.md
service-interconnect-operator/operator/overlays/stable/kustomization.yaml

Now Service interconnect Operator is available in stable channel.

Use Stable channel instead of Alpha one with Service interconnect Operator

---

openshift-data-foundation-operator/operator/base/openshift-data-foundation-console-plugin.yaml

The consolePlugin API has changed which means we need to update it for it to work with the newer versions.
The API has changed from **v1alpha1** to **v1**
Ref: https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html/console_apis/consoleplugin-console-openshift-io-v1
The **service** field now expects to be under **backend**
Ref: https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html/console_apis/consoleplugin-console-openshift-io-v1#spec-5

updated the ConsolePlugin for 4.18

---

openshift-gitops-operator/operator/base/kustomization.yaml

In general, components should rather appear in overlays, thus the change.
In this particular case there is also another issue, because enable-console-plugin component depends on GitOPS operator (e.g. openshift-gitops namespace must exist), which of course is not yet available, so kustomize will always throw errors whenever this component is used.

Remove component from operator base kustomization.yaml
